import { coinName } from './helpers';

export function generatePDFReport(coins) {
  const owned    = coins.filter(c => c.status === 'Own It');
  const totalEst = owned.reduce((s, c) => s + (parseFloat(c.estimatedValue) || 0), 0);
  const totalPaid = owned.reduce((s, c) => s + (parseFloat(c.paidPrice) || 0), 0);
  const date = new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });
  const fmt  = (n) => n.toLocaleString(undefined, { minimumFractionDigits:2, maximumFractionDigits:2 });

  const sorted = [...owned].sort((a, b) => (parseFloat(b.estimatedValue) || 0) - (parseFloat(a.estimatedValue) || 0));

  const rows = sorted.map(c => `
    <tr>
      <td>${coinName(c)}</td>
      <td style="text-align:center">${c.year || '—'}</td>
      <td style="text-align:center">${(c.mintMark || '').split('–')[0].trim() || 'P'}</td>
      <td style="text-align:center">${c.grade || '—'}</td>
      <td style="text-align:center">${c.copperColor || '—'}</td>
      <td style="text-align:center">${c.certified ? `${c.certService} #${c.certNumber}` : 'No'}</td>
      <td style="text-align:right;font-weight:bold">${c.estimatedValue ? '$' + Number(c.estimatedValue).toFixed(2) : '—'}</td>
      <td style="text-align:right">${c.paidPrice ? '$' + Number(c.paidPrice).toFixed(2) : '—'}</td>
      <td>${c.storageLocation || '—'}</td>
    </tr>
  `).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CoinVault Collection Report</title>
  <style>
    body { font-family: Georgia, serif; color: #1a1a1a; margin: 40px; }
    h1 { color: #8a6b1e; font-size: 24px; margin: 0 0 4px; }
    .subtitle { color: #666; font-size: 12px; margin: 0 0 24px; text-transform: uppercase; letter-spacing: .05em; }
    .stats { display: flex; gap: 24px; margin-bottom: 24px; padding: 16px; background: #faf8f4; border: 1px solid #e8e0cc; border-radius: 8px; }
    .stat { text-align: center; }
    .stat-val { font-size: 22px; font-weight: bold; color: #8a6b1e; }
    .stat-lbl { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: .08em; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #8a6b1e; color: white; padding: 8px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .08em; }
    td { padding: 6px 8px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #faf8f4; }
    .footer { margin-top: 24px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #ddd; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>⚡ CoinVault</h1>
  <div class="subtitle">Collection Insurance & Inventory Report · ${date}</div>
  <div class="stats">
    <div class="stat"><div class="stat-val">${owned.length}</div><div class="stat-lbl">Total Coins</div></div>
    <div class="stat"><div class="stat-val">$${fmt(totalEst)}</div><div class="stat-lbl">Est. Value</div></div>
    <div class="stat"><div class="stat-val">$${fmt(totalPaid)}</div><div class="stat-lbl">Invested</div></div>
    <div class="stat"><div class="stat-val">${owned.filter(c => c.certified).length}</div><div class="stat-lbl">Certified</div></div>
  </div>
  <table>
    <thead>
      <tr><th>Coin</th><th>Year</th><th>Mint</th><th>Grade</th><th>Color</th><th>Certified</th><th>Est. Value</th><th>Paid</th><th>Storage</th></tr>
    </thead>
    <tbody>${rows}</tbody>
    <tfoot>
      <tr>
        <td colspan="6" style="padding:8px;font-weight:bold;border-top:2px solid #8a6b1e">TOTAL</td>
        <td style="padding:8px;font-weight:bold;border-top:2px solid #8a6b1e;text-align:right">$${fmt(totalEst)}</td>
        <td style="padding:8px;font-weight:bold;border-top:2px solid #8a6b1e;text-align:right">$${fmt(totalPaid)}</td>
        <td style="border-top:2px solid #8a6b1e"></td>
      </tr>
    </tfoot>
  </table>
  <div class="footer">Generated by CoinVault · ${date} · Values are estimates for reference only</div>
</body>
</html>`;

  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
  setTimeout(() => w.print(), 500);
}
